In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [4]:
digits = load_digits()

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,random_state=42)

In [19]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\yashw\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9733333333333334

In [20]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [21]:
X=digits.data
y=digits.target
from sklearn.datasets import make_classification
X, y = make_classification(random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, y_train)  # apply scaling on training data
pipe.score(X_test, y_test) 

0.96

In [30]:
x=digits.data
y=digits.target
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(x_train, y_train)
pipe.score(x_test, y_test) 

0.9722222222222222

In [31]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test, y_test)

0.987037037037037

In [32]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [39]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [40]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [41]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [42]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\yashw\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [43]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.987037037037037

In [44]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.975925925925926

In [45]:
from sklearn.model_selection import StratifiedKFold

In [46]:
folds = StratifiedKFold(n_splits=3)

In [54]:
score_l =[]
score_svm = []
score_rf = []
for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    
    score_l.append(get_score(LogisticRegression(max_iter=5000),x_train,x_test,y_train,y_test))
    score_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

In [56]:
score_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [57]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [58]:
score_rf

[0.9348914858096828, 0.9532554257095158, 0.9315525876460768]

## cross_val_score

In [59]:
from sklearn.model_selection import cross_val_score

In [77]:
score_log = cross_val_score(LogisticRegression() , digits.data, digits.target)
score_log.mean()

C:\Users\yashw\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\yashw\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

0.9137650882079852

In [78]:
score_svm = cross_val_score(SVC() , digits.data, digits.target)
score_svm.mean()

0.9632838130609718

In [79]:
score=cross_val_score(RandomForestClassifier() , digits.data, digits.target)
score.mean()

0.9404688950789228