In [1]:
#Numpy->Numerical python
#gives us multi-dim array (nd array)

In [2]:
#A library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, 
#along with a large collection of high-level mathematical functions to operate on these arrays.

In [3]:
#Why Numpy is better then list:
# It takes less memory
import numpy as np

li_arr=[i for i in range(0,100)]
np_arr=np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [4]:
## Size of one element in numpy array:
print(np_arr.itemsize)

4


In [5]:
import sys

## size of one element in list
a=10
print(sys.getsizeof(a))

28


In [6]:
# Time exceution-> numpy array are much faster then 
# python normal list

import time
import numpy as np

size=100000
def addition_using_list():
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i]+b[i] for i in range(size)]
    t2=time.time()
    return(t2-t1)

def addition_using_numpy():
    t1=time.time()
    a=np.arange(size)
    b=np.arange(size)
    c=a+b
    t2=time.time()
    return(t2-t1)

t_list=addition_using_list()
t_numpy=addition_using_numpy()
print(t_list*1000)
print(t_numpy*1000)

94.53487396240234
2.9981136322021484


In [7]:
#numpy array are easy to use compared to list
#numpy have lot of functionality

In [8]:
#vectorization: we can apply mathematical operation over multiple elemetns
#at once rather than individual elements

#### Create Numpy arrays:

In [9]:
import numpy as np

#type:1
a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
a=[1,2,3,"abc",4.5]
b=np.array(a)
print(b)
#numpy can only contain element of same types
#bcoz of this each and every element is converted to string

['1' '2' '3' 'abc' '4.5']


In [12]:
a=[1,2,'43',4.5]
b=np.array(a,dtype=int)
print(b)

[ 1  2 43  4]


In [13]:
a=[1,2,3,'5']
b=np.array(a*3)
print(b)

['1' '2' '3' '5' '1' '2' '3' '5' '1' '2' '3' '5']


In [14]:
b=np.ones(3,dtype=int)
b

array([1, 1, 1])

In [15]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [16]:
b=np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
b=np.full((3,3),5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [19]:
b=np.empty(4)
b
#this gives array with size 4 with random numbers

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 0.00000000e+000])

In [20]:
l=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(l)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
b=np.zeros(10,dtype=int)
b[4]=1
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [22]:
#type:2
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b=np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b=np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
b=np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [26]:
b=np.linspace(2,10,5,dtype=int)
b

array([ 2,  4,  6,  8, 10])

In [27]:
b=np.identity(3)
b
#we get identity matrix of 3X3
#in identity we can only pass one argument

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
b=np.eye(4,5)
b
#in eye()we can pass two arguments

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [30]:
b=np.random.rand(3)
b
#we get random valuse between 0-1

array([0.22295201, 0.01284256, 0.86915986])

In [31]:
b=np.random.rand(4,3)
b

array([[0.64978563, 0.64633393, 0.88595178],
       [0.30148216, 0.26349901, 0.39991126],
       [0.79242744, 0.95707858, 0.98995646],
       [0.24961258, 0.03122837, 0.84890794]])

In [32]:
b=np.random.rand(10)*10
b

array([7.53976493, 6.58486266, 0.46009856, 7.147495  , 7.30516546,
       0.17736075, 4.88893976, 1.31915307, 8.07831654, 4.65817434])

In [33]:
b = np.random.randint(100)
print(b)

21


In [34]:
b = np.random.randint(0, 10)
print(b)

7


In [35]:
b = np.random.randint(0, 5, size=10)
print(b)

[2 4 4 1 4 0 3 4 4 1]


In [36]:
a=np.array([0,1,2,3,4])
a.shape

(5,)

In [37]:
b=np.random.randint(10,size=(4,4))
b
#this creates a random integer array ranging from 0 to
#10 of size(4,4)

array([[9, 5, 6, 6],
       [6, 6, 4, 7],
       [3, 6, 3, 3],
       [9, 9, 9, 2]])

In [38]:
b=np.random.randint(9,50,size=3)
b

array([32, 12, 33])

In [39]:
b=np.eye(5,6,dtype=int)
b

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [40]:
#cut the rope
b=np.linspace(0,5,9)
b

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

###### Basic properties

In [41]:
#numpy array is basically collection of references or collection of pointer
#with points to 4 diff attributes that are:
#1)data->reference to first byte of array i.e. fisrt element to array
#2)shape->size of array
#3)dtype->data type of element present inside array
#4)strides->number of bytes to be skipped to get to the next element


In [42]:
import numpy as np

li=[1,2,3,4,5]
arr=np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [43]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [44]:
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [45]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [46]:
import numpy as np

li=[1,2,3,4,5]
arr=np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [47]:
#access and slicing
#in 1-d array accesing one element and slicing is exactly same
print(li[3])
print(arr[3])
print(arr[1:4])

4
4
[2 3 4]


In [48]:
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [49]:
#accesing single element from 2-d array
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1]) #we can write this way also in 2d-nparray

10
10
10


In [50]:
#slicing in 2-d array
print(li_2d[1][:3])
print(arr_2d[1][:3])

[5, 6, 7]
[5 6 7]


In [51]:
print(li_2d[0:3][2])#in2-d list we cannot get part of coloumn through slicing
#we need to apply for loop to get it
#lets see what is happening here


[9, 10, 11, 12]


In [52]:
x=li_2d[0:3]
print(x)
y=x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [53]:
print(arr_2d[0:3,2])

[ 3  7 11]


In [54]:
print(arr_2d[2:4,1:3])

[[10 11]
 [14 15]]


In [55]:
#Problem statement
#2D integer array size(4,5)
list=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr=np.array(list)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [56]:
print(arr[2,0:3])

[11 12 13]


In [57]:
print(arr[1:4,3])

[ 9 14 19]


In [58]:
print(arr[2:4,0:6])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [59]:
print(arr[1:3,1:3])

[[ 7  8]
 [12 13]]


### Mathematical Operations

In [60]:
li=[1,2,3,4,5]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 3 14  2  2  6]
[16 18  9 10 18]


In [62]:
li =[i+1 for i in li] #to add 1 for all element in list
li

[3, 4, 5, 6, 7]

In [63]:
a=a+1 #to add 1 in all element of numpy.array(this method are vectorized)
a

array([ 4, 15,  3,  3,  7])

In [64]:
c=a+b
c

array([20, 33, 12, 13, 25])

In [65]:
d=a-b
d

array([-12,  -3,  -6,  -7, -11])

In [66]:
e=a*b
e

array([ 64, 270,  27,  30, 126])

In [67]:
f=a/b
f

array([0.25      , 0.83333333, 0.33333333, 0.3       , 0.38888889])

In [68]:
g=a//b
g

array([0, 0, 0, 0, 0])

In [69]:
h=a**b
h

array([          0,  2017564641,       19683,       59049, -1777531471])

In [70]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[ 4 15  3  3  7]
32
6.4
3
2
15
1


###### relational and logical operation also

In [71]:
print(a)
print(b)

[ 4 15  3  3  7]
[16 18  9 10 18]


In [72]:
a>b

array([False, False, False, False, False])

In [73]:
b>a

array([ True,  True,  True,  True,  True])

In [74]:
a==b

array([False, False, False, False, False])

In [75]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


## Boolean Indexing 1-D

In [76]:
import numpy as np

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[19 17  3  4 13  6  9 19]


In [77]:
print(b>10)

[ True  True False False  True False False  True]


In [78]:
bool_arr=b>10
print(bool_arr)
new_arr=b[bool_arr]
print(new_arr)

[ True  True False False  True False False  True]
[19 17 13 19]


In [79]:
#if we want element which are greater than 10
new_arr=b[b>10]
new_arr

array([19, 17, 13, 19])

In [80]:
#now to get element which are greater then 10 and less than 17
new_arr=b[(b>10) & (b<17)]
new_arr

array([13])

In [81]:
print(b)
c=b
c

[19 17  3  4 13  6  9 19]


array([19, 17,  3,  4, 13,  6,  9, 19])

In [82]:
c[:3]=19
c

array([19, 19, 19,  4, 13,  6,  9, 19])

In [83]:
c[c>15]=100
c

array([100, 100, 100,   4,  13,   6,   9, 100])

In [84]:
print(b)

[100 100 100   4  13   6   9 100]


In [85]:
print(b[b==100])

[100 100 100 100]


In [86]:
ind=np.where(b==100)
ind

(array([0, 1, 2, 7], dtype=int64),)

In [87]:
print(a[ind])

['t' 'b' 'r' 'a']


In [88]:
#non zero elements:
a=np.array([1,2,0,0,4,0])
ind=np.where(a!=0)
ind

(array([0, 1, 4], dtype=int64),)

In [89]:
#print multiples of 3(index):
a=np.array([1,3,5,7,9,11,13,15,17,19])
ind=np.where(a%3==0)
ind

(array([1, 4, 7], dtype=int64),)

In [90]:
#replace odd elements with -1
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2==1]=-1
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [91]:
#negate elements:
a=np.array([1,2,3,4,5,6,7,8,9,10])
new_arr = a[(a<3) | (a>8)]
new_arr

array([ 1,  2,  9, 10])

### Boolean indexing in 2-D

In [92]:
a=np.random.randint(1,30,(5,6))
print(a)

[[17 22 20  9  4  2]
 [22  2 27  8 17 22]
 [11 12  4  7 28 23]
 [16 26 17 16 21 22]
 [20 20 28 13  8  1]]


In [93]:
a>20

array([[False,  True, False, False, False, False],
       [ True, False,  True, False, False,  True],
       [False, False, False, False,  True,  True],
       [False,  True, False, False,  True,  True],
       [False, False,  True, False, False, False]])

In [94]:
bool_arr=a>20
ans=a[bool_arr]
print(ans)

[22 22 27 22 28 23 26 21 22 28]


In [95]:
b=a
print(b)

[[17 22 20  9  4  2]
 [22  2 27  8 17 22]
 [11 12  4  7 28 23]
 [16 26 17 16 21 22]
 [20 20 28 13  8  1]]


In [96]:
b[bool_arr]=100
print(b)

[[ 17 100  20   9   4   2]
 [100   2 100   8  17 100]
 [ 11  12   4   7 100 100]
 [ 16 100  17  16 100 100]
 [ 20  20 100  13   8   1]]


In [97]:
bool_arr=b[:,3]==100
print(bool_arr)

[False False False False False]


In [98]:
b[bool_arr,3]=99
print(b)

[[ 17 100  20   9   4   2]
 [100   2 100   8  17 100]
 [ 11  12   4   7 100 100]
 [ 16 100  17  16 100 100]
 [ 20  20 100  13   8   1]]


In [99]:
#sort by coloumn:
b = np.array([[21, 20, 19, 18, 17],
              [16, 15, 14, 13, 12],
              [11, 10, 9, 8, 7],
              [6, 5, 4, 3, 2]])
print(b)

#NEED TO DO

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]


### Numpy Broadcasting

In [100]:
#broadcasting actually describes who numpy will treat unequal size arrays

In [101]:
#X(3,2) and y(3,2) =>compatible
#x(3,3) and y(3,2) => not compatible
#x(3,3) and y(1,3) =>compatible

In [102]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)

[[4 8 9]
 [5 1 2]
 [5 5 3]]
[[7 6 5]
 [6 9 2]
 [4 3 2]]


In [103]:
ans=x-y
print(ans)

[[-3  2  4]
 [-1 -8  0]
 [ 1  2  1]]


In [104]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3))
print(x)
print(y)

[[3 9 5]
 [8 7 4]
 [6 8 7]]
[8 3 5]


In [105]:
ans=x-y
print(ans) #using broadcasting we get no error in ans
#broadcasting is repeating one row 3 times so that we can perform
#element by element operation

[[-5  6  0]
 [ 0  4 -1]
 [-2  5  2]]


In [106]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(2,3))
print(x)
print(y)

[[3 8]
 [8 4]
 [5 3]]
[[2 1 4]
 [1 6 9]]


In [107]:
y=np.transpose(y)
print(y)
ans=x-y
print(ans)

[[2 1]
 [1 6]
 [4 9]]
[[ 1  7]
 [ 7 -2]
 [ 1 -6]]


In [108]:
# resize() and reshape() functions

In [109]:
#examples:
#    (3,1) and (3,3)
# (1,3) and (3,1)
# (1,3) and (1,1)
#this will become compatible by broadcasting

## year2017

In [151]:
#need to create a new coloumn with killed+wounded
import csv
file_path=('Dataset/year2017.csv')
with open(file_path,'r') as file_obj:
    data=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    wounded=[]
    country=[]
    for row in data:
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        country.append(row['Country'])
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_country=np.array(country)
#replacing empty values with zero
np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'
np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)

killed_wounded=np_wounded+np_killed
print(killed_wounded)

# finding wonded+killed for india
bool_arr= np_country=='India'
ans=killed_wounded[bool_arr]
print(np.sum(ans))
print(np.sum(killed_wounded))

[0. 2. 7. ... 0. 0. 0.]
1167.0
51372.0
